In [1]:
import torch
a = torch.rand(4,3,28,28) #CNN中的tensor【batch,channel,height,weigth】


取第一个索引的维度，表示取第零张图片的size

In [2]:
a[0].shape

torch.Size([3, 28, 28])

取第零张图片，第零个通道的维度

In [3]:
a[0,0].shape

torch.Size([28, 28])

取第零张图片，第零个通道，第2行，第4列的像素

In [4]:
a[0,0,2,4]

tensor(0.1113)

In [5]:
a.shape

torch.Size([4, 3, 28, 28])

# 用:的索引方式
四种连续片段索引方式：  
1, :   ：表示取全部的值，可理解为一个→   
2, :n  :表示从第0到n，不包括n  
3, n:  :表示从n到末尾不包含第n个值，反向索引时索引号从右到左为-1,-2,...,-n  
4,  :  : n ：表示从0到末尾隔行取值，间隔为n  


### :n 索引

把:理解为一个→，a[:2]表示从[0,2)的区间取值，即第0张和第1张图片的size

In [6]:
a[:2].shape

torch.Size([2, 3, 28, 28])

### :n,:,:  索引

取第0,1张图片在第0个channel，不包括第1个channel的size

In [7]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

### n: 索引

In [8]:
a[:2,1:,:,:].shape

torch.Size([2, 2, 28, 28])

channel 所在的维度索引从左到右是0,1,2，从右到左是-1,-2,-3

In [9]:
a[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

### : : n  索引

In [10]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [11]:
a[:,:,::2,::2].shape #与上面一行的代码具有同样的效果

torch.Size([4, 3, 14, 14])

# 用index_select()函数索引

In [12]:
a.shape

torch.Size([4, 3, 28, 28])

In [13]:
a.index_select(0,torch.tensor([0,2])).shape

torch.Size([2, 3, 28, 28])

In [14]:
a.index_select(1,torch.tensor([1,2])).shape

torch.Size([4, 2, 28, 28])

In [15]:
a.index_select(2,torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [16]:
a.index_select(2,torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

# 用...  索引
表示任意多的维度，具体代表多少维度据情况而定

In [17]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [18]:
a[0,...].shape #等于a[0]

torch.Size([3, 28, 28])

In [19]:
a[:,1,...].shape #等于a[:,1]

torch.Size([4, 28, 28])

In [20]:
a[...,:2].shape #等于a[:,:,:,2]

torch.Size([4, 3, 28, 2])

# 用mask（掩码）索引
用此方法可以将tensor中的值按照数值的大小进行取值，比如提取比1大的数值，此方法平时用得不多

In [21]:
x = torch.randn(3,4)
print(x)

tensor([[ 1.1076,  0.4816, -0.0627,  2.3158],
        [-0.1906, -0.3179, -0.9156,  0.6239],
        [ 0.5247, -0.1649,  0.2962, -0.0256]])


In [22]:
mask = x.ge(0.5)  #大于等于0.5的值设为1，其他为0
mask

tensor([[1, 0, 0, 1],
        [0, 0, 0, 1],
        [1, 0, 0, 0]], dtype=torch.uint8)

In [23]:
torch.masked_select(x, mask)

tensor([1.1076, 2.3158, 0.6239, 0.5247])

In [24]:
torch.masked_select(x,mask).shape

torch.Size([4])

# 用take（）函数将tensor展成向量再索引

In [25]:
src = torch.tensor([[4,3,5],[6,7,8]])
src 

tensor([[4, 3, 5],
        [6, 7, 8]])

In [27]:
torch.take(src, torch.tensor[0,2])

TypeError: 'builtin_function_or_method' object is not subscriptable